GroupingSystem/Models/Event.cs
namespace GroupingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Event
    {


        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(50)]
        public string Location { get; set; }

        [Column("Tickets available")]
        public int Tickets_available { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Time { get; set; }

        public string eventAndTicketsAndDate { get { return "Event: " + " " + Name +  " | Date:  " + Date.ToString("dd/MM/yyyy") + " " + Time.ToString("HH:mm") + " | Tickets Available: " + Tickets_available; } }
    }
}

GroupingSystem/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GroupingSystem.Models;

namespace GroupingSystem.Controllers
{
    public class EventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // Get events to show based on if searching for a location or not
        [Authorize]
        public async Task<ActionResult> Index(string locSearch)
        {
            var events = from e in db.Events
                         where (e.Tickets_available > 0)
                         select e;

            var filtEvents = from v in events
                             where v.Date > DateTime.Now
                             select v;

            if(locSearch != null)
            {
                var locationEvents = from e in filtEvents
                                     where e.Location.ToUpper() == locSearch.ToUpper()
                                     select e;
                ViewBag.totalEvents = locationEvents.Count();
                locSearch = locSearch.ToLower();
                ViewBag.searchedLocation = char.ToUpper(locSearch[0]) + locSearch.Substring(1); ;
                return View(await locationEvents.ToListAsync());
            }

            return View(await filtEvents.ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        // GET: Events/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = await db.Events.FindAsync(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        [Authorize(Roles = "Admin")]
        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name,Location,Date,Time,Tickets_available")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        [Authorize(Roles = "Admin")]
        // GET: Events/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = await db.Events.FindAsync(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        [Authorize(Roles = "Admin")]
        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Location,Date,Time,Tickets_available")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        [Authorize(Roles = "Admin")]
        // GET: Events/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = await db.Events.FindAsync(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        [Authorize(Roles = "Admin")]
        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Event @event = await db.Events.FindAsync(id);
            db.Events.Remove(@event);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GroupingSystem/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GroupingSystem.Models;

namespace GroupingSystem.Controllers
{
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        // Show groups based on the selected filtering options
        public async Task<ActionResult> Index(int? evSearch, bool? myGroups)
        {
            var eventList = from e in db.Events
                            select e;


            var events = from e in db.Events
                         where (e.Tickets_available > 0)
                         select e;

            var filtEvents = from v in events
                             where v.Date > DateTime.Now
                             select v;

            ViewBag.eventsList = await eventList.ToListAsync();

            ViewBag.Events = new SelectList(filtEvents, "Id", "eventAndTicketsAndDate");

            //if searching for a specific event
            if (evSearch != null)
            {
                if(myGroups == true)
                {
                    ViewBag.searchResult = "Currently searching for your groups for event" + evSearch;
                    ViewBag.groupCount = (db.Groups.Where(x => x.eventId == evSearch).Where(x => new[] { x.groupOwner, x.member1, x.member2, x.member3, x.member4 }.Any(s => s.Contains(User.Identity.Name)))).Count();
                    return View(db.Groups.Where(x => x.eventId == evSearch).Where(x => new[] { x.groupOwner, x.member1, x.member2, x.member3, x.member4 }.Any(s => s.Contains(User.Identity.Name))));
                }
                else
                {
                    ViewBag.searchResult = "Currently searching for groups for event" + evSearch;
                    ViewBag.groupCount = (db.Groups.Where(x => x.eventId == evSearch)).Count();
                    return View(db.Groups.Where(x => x.eventId == evSearch));
                }
            }

            //if not searching for a specific event
            if (evSearch == null)
            {
                if(myGroups == true)
                {
                    ViewBag.searchResult = "Currently searching for your groups" + evSearch;
                    ViewBag.groupCount = (db.Groups.Where(x => new[] { x.groupOwner, x.member1, x.member2, x.member3, x.member4 }.Any(s => s.Contains(User.Identity.Name)))).Count();
                    return View(db.Groups.Where(x => new[] { x.groupOwner, x.member1, x.member2, x.member3, x.member4 }.Any(s => s.Contains(User.Identity.Name))));
                }
                else
                {
                    ViewBag.searchResult = "Currently showing all groups";
                    ViewBag.groupCount = (db.Groups.Where(x => x.Id >= 0)).Count();
                    return View(await db.Groups.ToListAsync());
                }
            }

            ViewBag.searchResult = "Currently showing all groups";
            ViewBag.groupCount = (db.Groups.Where(x => x.Id >= 0)).Count();


            return View(await db.Groups.ToListAsync());

        }


        [Authorize]
        // GET: Groups/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FindAsync(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        [Authorize]
        // Open create group view and create a list of currently available events to pass to drop down box
        public ActionResult Create()
        {

            var events = from e in db.Events
                         where (e.Tickets_available > 0)
                         select e;

            var filtEvents = from v in events
                             where v.Date > DateTime.Now
                             select v;

            ViewBag.Events = new SelectList(filtEvents, "Name", "eventAndTicketsAndDate");
            return View();
        }


        [Authorize]
        //open submit group view
        public async Task<ActionResult> SubmitGroup(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = await db.Groups.FindAsync(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        //Submit the group to the submitted groups list for approval
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SubmitGroup([Bind(Include = "Id,groupName,groupSize,groupOwner,member1,member2,member3,member4,submitted,groupDescription,groupEvent,eventId")]  Group subGroup)
        {

            if (ModelState.IsValid)
            {
                //Sending messages to the inbox of users in the relevent fields to say that the group has been submitted
                    if (subGroup.groupOwner != null)
                {
                    var message = new Message
                    {
                        User = subGroup.groupOwner,
                        Message1 = "Hi " + subGroup.groupOwner + ", " + "Your group " + subGroup.groupName + " for event " + subGroup.groupEvent + " has been submitted for approval",
                        Seen = false,
                        Subject = "Group submitted",
                        From = "Admin",
                        Time = DateTime.Now
                };
                    db.Messages.Add(message);
                }
                if (subGroup.member1 != null)
                {
                    var message = new Message
                    {
                        User = subGroup.member1,
                        Message1 = "Hi " + subGroup.groupOwner + ", " + "Your group " + subGroup.groupName + " for event " + subGroup.groupEvent + " has been submitted for approval",
                        Seen = false,
                        Subject = "Group submitted",
                        From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                }
                if (subGroup.member2 != null)
                {
                    var message = new Message
                    {
                        User = subGroup.member2,
                        Message1 = "Hi " + subGroup.groupOwner + ", " + "Your group " + subGroup.groupName + " for event " + subGroup.groupEvent + " has been submitted for approval",
                        Seen = false,
                        Subject = "Group submitted",
                        From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                }
                if (subGroup.member3 != null)
                {
                    var message = new Message
                    {
                        User = subGroup.member3,
                        Message1 = "Hi " + subGroup.groupOwner + ", " + "Your group " + subGroup.groupName + " for event " + subGroup.groupEvent + " has been submitted for approval",
                        Seen = false,
                        Subject = "Group submitted",
                        From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                }
                if (subGroup.member4 != null)
                {
                    var message = new Message
                    {
                        User = subGroup.member4,
                        Message1 = "Hi " + subGroup.groupOwner + ", " + "Your group " + subGroup.groupName + " for event " + subGroup.groupEvent + " has been submitted for approval",
                        Seen = false,
                        Subject = "Group submitted",
                        From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                }

                //create submitted group to enter to table
            var submitted = new SubmittedGroup
            {
                GroupID = subGroup.Id,
                groupOwner = subGroup.groupOwner,
                groupEvent = subGroup.groupEvent,
                eventId = subGroup.eventId
            };


                subGroup.submitted = true;
                db.Entry(subGroup).State = EntityState.Modified;
                db.SubmittedGroups.Add(submitted);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(subGroup);
        }






        [Authorize]
        // Submit the group creation
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "groupName,groupDescription,groupSize,groupOwner,groupEvent, eventId")] Group newGroup)
        {
           
            Event eventChecked = new Event();

            //reinitialise the drop down list of events to get value
            var events = from e in db.Events
                         where (e.Tickets_available > 0)
                         select e;

            var filtEvents = from v in events
                             where v.Date > DateTime.Now
                             select v;

            ViewBag.Events = new SelectList(filtEvents, "Name", "eventAndTicketsAndDate");

GroupingSystem/Views/Events/Create.cshtml
@model GroupingSystem.Models.Event

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create an event</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tickets_available, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tickets_available, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tickets_available, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, "{0:d}", new { htmlAttributes = new { @class = "datepicker", type = "text", autocomplete = "off", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

@*set datepicker to only future dates within the next 10 years*@
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section Scripts {
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $(".datepicker").datepicker({
                dateFormat: 'dd/mm/yy',
                changeYear: true,
                changeMonth: true,
                yearRange: '0:+10',
                minDate: 0
            });
        });
    </script>
}

GroupingSystem/Views/Events/Delete.cshtml
@model GroupingSystem.Models.Event

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tickets_available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tickets_available)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GroupingSystem/Views/Events/Details.cshtml
@model GroupingSystem.Models.Event

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tickets_available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tickets_available)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GroupingSystem/Views/Events/Edit.cshtml
@model GroupingSystem.Models.Event

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Event</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tickets_available, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tickets_available, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tickets_available, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, "{0:d}", new { htmlAttributes = new { @class = "datepicker", type = "text", autocomplete = "off", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroupingSystem/Views/Events/Index.cshtml
@model IEnumerable<GroupingSystem.Models.Event>
<link href="~/Content/Site.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*Div for filtering options and post to controller*@
<div style="text-align: center">
    @using (Html.BeginForm("Index", "Events", FormMethod.Get))
    {
        <span>Select an event: </span> <input type="text" id="locSearch" , name="locSearch" value="" /> <span>  </span>
        <input type="submit" value="Search for Location" /> @Html.ActionLink("Reset search", "Index", "Events", null, new { @class = "btn btn-primary btn-large" }) <div style=" margin-bottom: 5px;">
        </div><br />
    }
    @if (ViewBag.searchedLocation != null)
    {
       @ViewBag.totalEvents <span> event found in </span> @ViewBag.searchedLocation
    }

</div>
@*allow admins to see create event button*@
@if (User.IsInRole("Admin"))
{
    @Html.ActionLink("Create New Event", "Create", "Events", null, new { @class = "btn btn-primary btn-large" })
}
<table class="table table-condensed groupTable">
    <tr>
        <th>
            Event
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)           
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date) and time
        </th>
        <th>
            Available Tickets
        </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date) @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tickets_available)
        </td>
        <td>
            @Html.ActionLink("Make group", "CreateFromEvent", "Groups", new { id = item.Id }, null)
        </td>
        @if (User.IsInRole("Admin"))
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        }

    </tr>
    }

</table>