GroupingSystem/Models/UserProfile.cs
namespace GroupingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class UserProfile
    {
        public int Id { get; set; }

        public string firstName { get; set; }

        public string lastName { get; set; }

        public string email { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DoB { get; set; }

        public string username { get; set; }

        public bool privateProfile { get; set; }

        public bool privateDoB { get; set; }

        public bool privateBadges { get; set; }

        public bool privateEvents { get; set; }
    }
}

GroupingSystem/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GroupingSystem.Models;
using System.Diagnostics;

namespace GroupingSystem.Controllers
{
    public class UserProfilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserProfiles
        public async Task<ActionResult> Index()
        {
            return View(await db.UserProfiles.ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        // GET: UserProfiles/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = await db.UserProfiles.FindAsync(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }


            return View(userProfile);
        }

        //view selected user's profile
        [Authorize]
        public async Task<ActionResult> viewProfile(string id)
        {
  
           int? idFind = db.UserProfiles.Where(x => x.username == id).SingleOrDefault()?.Id;

           UserProfile foundProfile = await db.UserProfiles.FindAsync(idFind);
           
            //find approved groups where the user is mentioned
            var findGroups = (from g in db.Groups
                              where g.groupOwner == foundProfile.username || g.member1 == foundProfile.username || g.member2 == foundProfile.username || g.member3 == foundProfile.username || g.member4 == foundProfile.username
                              select g);

            var findApprovedGroups = (from a in db.SubmittedGroups
                                      where a.Approved == true
                                      select a);

            var listOfAttendedEvents = new List<Group>();

            //populate list of recent events
            foreach (var a in findApprovedGroups)
            {
                foreach(var g in findGroups)
                {
                    if(a.GroupID == g.Id)
                    {
                        listOfAttendedEvents.Add(g);
                    }
                }

            }
            
            //Set to 5 most recent events
            ViewBag.eventsAttended = listOfAttendedEvents.Count;
            ViewBag.privacyId = foundProfile.Id;
            var recentEvents = listOfAttendedEvents.Skip(Math.Max(0, listOfAttendedEvents.Count() - 5));

            ViewBag.groupsAttended = recentEvents;

            //get privacy settings
            ViewBag.Privacy = foundProfile.privateProfile;
            ViewBag.DoBPrivacy = foundProfile.privateDoB;
            ViewBag.BadgePrivacy = foundProfile.privateBadges;
            ViewBag.EventPrivacy = foundProfile.privateEvents;

            return View(foundProfile);

        }

        [Authorize(Roles = "Admin")]
        // GET: UserProfiles/Create
        public ActionResult Create()
        {
            return View();
        }


        [Authorize(Roles = "Admin")]
        // POST: UserProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,firstName,lastName,email,DoB,username")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userProfile);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(userProfile);
        }

        [Authorize(Roles = "Admin")]
        // GET: UserProfiles/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = await db.UserProfiles.FindAsync(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        [Authorize(Roles = "Admin")]
        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,firstName,lastName,email,DoB,username")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userProfile).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(userProfile);
        }

        [Authorize]
        // open edit privacy view
        public async Task<ActionResult> EditPrivacy(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = await db.UserProfiles.FindAsync(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }

            if(userProfile.username == User.Identity.Name)
            {
                return View(userProfile);
            }
            else
            {
                return HttpNotFound();
            }
        }
        [Authorize]
        // Submit modified privacy settings
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditPrivacy([Bind(Include = "Id,firstName,lastName,email,DoB,username,privateProfile, privateDoB, privateBadges, privateEvents")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userProfile).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("ViewProfile/" + userProfile.username);
            }
            return View(userProfile);
        }


        [Authorize(Roles = "Admin")]
        // GET: UserProfiles/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = await db.UserProfiles.FindAsync(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        [Authorize(Roles = "Admin")]
        // POST: UserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            UserProfile userProfile = await db.UserProfiles.FindAsync(id);
            db.UserProfiles.Remove(userProfile);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GroupingSystem/Views/UserProfiles/Create.cshtml
@model GroupingSystem.Models.UserProfile

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserProfile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroupingSystem/Views/UserProfiles/Delete.cshtml
@model GroupingSystem.Models.UserProfile

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GroupingSystem/Views/UserProfiles/Details.cshtml
@model GroupingSystem.Models.UserProfile

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GroupingSystem/Views/UserProfiles/Edit.cshtml
@model GroupingSystem.Models.UserProfile

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserProfile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DoB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DoB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroupingSystem/Views/UserProfiles/EditPrivacy.cshtml
@model GroupingSystem.Models.UserProfile

@{
    ViewBag.Title = "EditPrivacy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditPrivacy</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>UserProfile</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.firstName)
    @Html.HiddenFor(model => model.lastName)
    @Html.HiddenFor(model => model.email)
    @Html.HiddenFor(model => model.DoB)
    @Html.HiddenFor(model => model.username)

    <div class="form-group">
        @Html.LabelFor(model => model.privateProfile,"Private profile", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.privateProfile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.privateProfile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.privateDoB,"Private Date of Birth" ,htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.privateDoB, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.privateDoB, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.privateEvents, "Private Events", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.privateEvents, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.privateEvents, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.privateBadges,"Private Badges", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.privateBadges, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.privateBadges, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

GroupingSystem/Views/UserProfiles/Index.cshtml
@model IEnumerable<GroupingSystem.Models.UserProfile>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DoB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.username)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.firstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DoB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.username)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
            @Html.ActionLink("View", "viewProfile", new { id = item.username })
        </td>
    </tr>
}

</table>

GroupingSystem/Views/UserProfiles/viewProfile.cshtml
@model GroupingSystem.Models.UserProfile

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*Check if profile is private and output accordingly*@
@if (ViewBag.Privacy == false || (User.Identity.Name == Model.username || User.IsInRole("Admin")))
{
    <h2>User Details</h2>
    <div class="row">
        <div class="col-md-4">
            <section id="profileDetails">
                @*Check user viewing profile is the owner and display button to edit privacy settings*@
                @if (Model.username == User.Identity.Name)
                {
                    string privacyString = "EditPrivacy/" + Model.Id;
                    @Html.ActionLink("Edit privacy settings", privacyString, "UserProfiles",null,new { @class = "btn btn-primary btn-large" })
                }
                @*output profile details*@
                <dl class="dl-horizontal">
                    <dt>
                        Username:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.username)
                    </dd>
                    <dt>
                        Name:
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.firstName) @Html.DisplayFor(model => model.lastName)
                    </dd>
                    @*Check date of birth privacy and hide if enabled*@
                    @if (ViewBag.DoBPrivacy == false || (User.Identity.Name == Model.username || User.IsInRole("Admin")))
                    {
                        <dt>
                            Date of Birth:
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.DoB)
                        </dd>
                    }

                    @*Add button to message user if not account owner*@
                    @if (Model.username != User.Identity.Name)
                    {
                        <dd>
                            @Html.ActionLink("Message user", "Create", "Messages", new { user = Model.username }, null)
                        </dd>
                    }

                </dl>
            </section>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            @*Check recent event privacy and output accordingly*@
            @if (ViewBag.EventPrivacy == false || (User.Identity.Name == Model.username || User.IsInRole("Admin")))
            {
                <h3>Recently Attended Events </h3>
                <section id="eventShowcase">
                    @foreach (var g in ViewBag.groupsAttended)
                    {
                        <div>
                            @g.groupName
                            @g.groupEvent
                        </div>
                    }
                </section>
            }
            else
            {
                <h3>
                    This user's events are private.
                </h3>
            }
        </div>
        <div class="col-md-6">
            @*Check badge privacy and output accordingly*@
            @if (ViewBag.BadgePrivacy == false || (User.Identity.Name == Model.username || User.IsInRole("Admin")))
            {
                <section id="eventBadges">
                    <h3> Badges </h3>
                    <div>

                        @if (ViewBag.eventsAttended >= 1)
                        {
                            <span>Events attended:</span>
                            <img src="@Url.Content("~/Content/badges/1OrMore.jpg")" />

                        }
                        @if (ViewBag.eventsAttended >= 3)
                        {

                            <img src="@Url.Content("~/Content/badges/3OrMore.jpg")" />

                        }
                        @if (ViewBag.eventsAttended >= 5)
                        {

                            <img src="@Url.Content("~/Content/badges/5OrMore.jpg")" />

                        }
                    </div>
                </section>
            }
            else
            {
                <h3>
                    This user's badges are private.
                </h3>
            }

        </div>
    </div>
}
                    @if(ViewBag.Privacy == true && User.Identity.Name != Model.username)
                    {
                     <h2>Sorry, this profile is private.</h2>
                    }