GroupingSystem/Models/SubmittedGroup.cs
namespace GroupingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class SubmittedGroup
    {
        public int Id { get; set; }

        public int GroupID { get; set; }

        public bool Approved { get; set; }

        public bool Denied { get; set; }

        public string groupOwner { get; set; }

        public string groupEvent { get; set; }

        public int eventId { get; set; }
    }
}

GroupingSystem/Controllers/SubmittedGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GroupingSystem.Models;

namespace GroupingSystem.Controllers
{
    public class SubmittedGroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "Admin")]
        // Show submitted groups and filter if necessary
        public async Task<ActionResult> Index(bool? filterOut)
        {


            if (filterOut == true)
                    {
                     return View(db.SubmittedGroups.Where(x => x.Approved == false).Where(x => x.Denied == false));
                    }
                    else
                    {
                    return View(await db.SubmittedGroups.ToListAsync());
               }

        }

        [Authorize(Roles = "Admin")]
        // GET: SubmittedGroups/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubmittedGroup submittedGroup = await db.SubmittedGroups.FindAsync(id);
            if (submittedGroup == null)
            {
                return HttpNotFound();
            }
            return View(submittedGroup);
        }

        [Authorize(Roles = "Admin")]
        // GET: SubmittedGroups/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: SubmittedGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,GroupID,Approved,Denied,groupOwner,groupEvent")] SubmittedGroup submittedGroup)
        {
            if (ModelState.IsValid)
            {
                db.SubmittedGroups.Add(submittedGroup);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(submittedGroup);
        }

        [Authorize(Roles = "Admin")]
        // GET: SubmittedGroups/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubmittedGroup submittedGroup = await db.SubmittedGroups.FindAsync(id);
            if (submittedGroup == null)
            {
                return HttpNotFound();
            }
            return View(submittedGroup);
        }

        [Authorize(Roles = "Admin")]
        // POST: SubmittedGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,GroupID,Approved,Denied,groupOwner,groupEvent")] SubmittedGroup submittedGroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(submittedGroup).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(submittedGroup);
        }

        [Authorize(Roles = "Admin")]
        // GET: SubmittedGroups/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubmittedGroup submittedGroup = await db.SubmittedGroups.FindAsync(id);
            if (submittedGroup == null)
            {
                return HttpNotFound();
            }
            return View(submittedGroup);
        }

        [Authorize(Roles = "Admin")]
        // POST: SubmittedGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SubmittedGroup submittedGroup = await db.SubmittedGroups.FindAsync(id);
            db.SubmittedGroups.Remove(submittedGroup);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //approve a group view
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Approve(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubmittedGroup submittedGroup = await db.SubmittedGroups.FindAsync(id);
            if (submittedGroup == null)
            {
                return HttpNotFound();
            }

            //find the group to approve
            int? groupIdFind = db.Groups.Where(x => x.Id == submittedGroup.GroupID).SingleOrDefault()?.Id;          
            Group foundGroup = await db.Groups.FindAsync(groupIdFind);
            ViewBag.chosenGroup = foundGroup;
            return View(submittedGroup);
        }

        //approve the group
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Approve([Bind(Include = "Id,GroupID,Approved,Denied,groupOwner,groupEvent,eventId")] SubmittedGroup groupSubmitted)
        {
            if (ModelState.IsValid)
            {

                //find the event the group is attending
                int? eventIdFind = db.Events.Where(x => x.Id == groupSubmitted.eventId).SingleOrDefault()?.Id;

                Event foundEvent = await db.Events.FindAsync(eventIdFind);

                //find the group
                int? groupIdFind = db.Groups.Where(x => x.Id == groupSubmitted.GroupID).SingleOrDefault()?.Id;

                Group foundGroup = await db.Groups.FindAsync(groupIdFind);



                int available = foundEvent.Tickets_available;
                int deduction = 0;

                //count tickets to decuct from event total and message the members of the group that the group has been approved
                if(foundGroup.groupOwner != null)
                {
                    var message = new Message
                    {
                    User = foundGroup.groupOwner,
                    Message1 = "Hi " + foundGroup.groupOwner + ", " + "Your group " + foundGroup.groupName + " for event " + foundGroup.groupEvent + " has been approved",
                    Seen = false,
                    Subject = "Group approved",
                    From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                    deduction = deduction + 1;
                }
                if (foundGroup.member1 != null)
                {
                    var message = new Message
                    {
                        User = foundGroup.member1,
                        Message1 = "Hi " + foundGroup.groupOwner + ", " + "Your group " + foundGroup.groupName + " for event " + foundGroup.groupEvent + " has been approved",
                        Seen = false,
                        Subject = "Group approved",
                        From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                    deduction = deduction + 1;
                }
                if (foundGroup.member2 != null)
                {
                    var message = new Message
                    {
                        User = foundGroup.member2,
                        Message1 = "Hi " + foundGroup.groupOwner + ", " + "Your group " + foundGroup.groupName + " for event " + foundGroup.groupEvent + " has been approved",
                        Seen = false,
                        Subject = "Group approved",
                        From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                    deduction = deduction + 1;
                }
                if (foundGroup.member3 != null)
                {
                    var message = new Message
                    {
                        User = foundGroup.member3,
                        Message1 = "Hi " + foundGroup.groupOwner + ", " + "Your group " + foundGroup.groupName + " for event " + foundGroup.groupEvent + " has been approved",
                        Seen = false,
                        Subject = "Group approved",
                        From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                    deduction = deduction + 1;
                }
                if (foundGroup.member4 != null)
                {
                    var message = new Message
                    {
                        User = foundGroup.member4,
                        Message1 = "Hi " + foundGroup.groupOwner + ", " + "Your group " + foundGroup.groupName + " for event " + foundGroup.groupEvent + " has been approved",
                        Seen = false,
                        Subject = "Group approved",
                        From = "Admin",
                        Time = DateTime.Now
                    };
                    db.Messages.Add(message);
                    deduction = deduction + 1;
                }

                //deduct tickets and modify group to approved
                foundEvent.Tickets_available = available - deduction;
                groupSubmitted.Approved = true;
                db.Entry(groupSubmitted).State = EntityState.Modified;

GroupingSystem/Views/SubmittedGroups/Approve.cshtml
@model GroupingSystem.Models.SubmittedGroup
<link rel="stylesheet" type="text/css" href="~/Content/Site.css">
@{
    ViewBag.Title = "Approve";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Are you sure that you wish to Approve this group?</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @*Output the group's information*@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.GroupID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.HiddenFor(model => model.GroupID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.DisplayFor(model => model.GroupID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.groupOwner, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.HiddenFor(model => model.groupOwner, new { htmlAttributes = new { @class = "form-control" } })
            @Html.DisplayFor(model => model.groupOwner, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.groupOwner, "", new { @class = "text-danger" })
        </div>
    </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.groupOwner,"Group members", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @ViewBag.chosenGroup.member1
                @ViewBag.chosenGroup.member2
                @ViewBag.chosenGroup.member3
                @ViewBag.chosenGroup.member4
            </div>
        </div>

    <div class="form-group">
        @Html.LabelFor(model => model.groupEvent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.HiddenFor(model => model.groupEvent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.DisplayFor(model => model.groupEvent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.groupEvent, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(model => model.eventId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.eventId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Approve Group" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroupingSystem/Views/SubmittedGroups/Create.cshtml
@model GroupingSystem.Models.SubmittedGroup

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubmittedGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Approved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Approved)
                    @Html.ValidationMessageFor(model => model.Approved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Denied, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Denied)
                    @Html.ValidationMessageFor(model => model.Denied, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.groupOwner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupOwner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupOwner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.groupEvent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupEvent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupEvent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroupingSystem/Views/SubmittedGroups/Delete.cshtml
@model GroupingSystem.Models.SubmittedGroup

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubmittedGroup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Approved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Approved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Denied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Denied)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.groupOwner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupOwner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.groupEvent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupEvent)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GroupingSystem/Views/SubmittedGroups/Deny.cshtml
@model GroupingSystem.Models.SubmittedGroup

@{
    ViewBag.Title = "Deny";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deny</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*Output the groups details*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Approved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Approved)
                    @Html.ValidationMessageFor(model => model.Approved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Denied, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Denied)
                    @Html.ValidationMessageFor(model => model.Denied, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.groupOwner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupOwner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupOwner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.groupEvent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupEvent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupEvent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Deny Group" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroupingSystem/Views/SubmittedGroups/Details.cshtml
@model GroupingSystem.Models.SubmittedGroup

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SubmittedGroup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Approved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Approved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Denied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Denied)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.groupOwner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupOwner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.groupEvent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupEvent)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GroupingSystem/Views/SubmittedGroups/Edit.cshtml
@model GroupingSystem.Models.SubmittedGroup

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubmittedGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Approved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Approved)
                    @Html.ValidationMessageFor(model => model.Approved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Denied, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Denied)
                    @Html.ValidationMessageFor(model => model.Denied, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.groupOwner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupOwner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupOwner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.groupEvent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupEvent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupEvent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GroupingSystem/Views/SubmittedGroups/Index.cshtml
@model IEnumerable<GroupingSystem.Models.SubmittedGroup>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Submitted groups</h2>
@*Div for filtering to send to controller*@
@using (Html.BeginForm("Index", "SubmittedGroups", FormMethod.Get))
{
    <span>Filter out approved/denied groups: </span>@Html.CheckBox("filterOut", false);<span>  </span><br />
    <input type="submit" value="Apply" /> @Html.ActionLink("Reset filter", "Index", "SubmittedGroups", null, new { @class = "btn btn-primary btn-large" }) <div style=" margin-bottom: 5px;">
    </div><br />
}
<table class="table table-condensed groupTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GroupID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.groupOwner)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.groupEvent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Approved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Denied)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.groupOwner)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.groupEvent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Approved)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Denied)
            </td>

            <td>
                @if (item.Approved == false && item.Denied == false)
                {
                    @Html.ActionLink("Approve", "Approve", new { id = item.Id })<span> | </span>
                    @Html.ActionLink("Deny", "Deny", new { id = item.Id })
                }
            </td>
        </tr>
    }

</table>